#!/usr/bin/env python3
"""
Team-Name-zu-Slug-Konverter - Portierung der App-Logik
Konvertiert Team-Namen zu fussballdaten.de URL-Slugs
"""

import re
import unicodedata
from typing import Optional, Dict

# Rate Limiting: Reduziert von 1.0 auf 0.5 Sekunden für schnellere Scraping (25min → ~12min)
REQUEST_DELAY = 0.5

def get_liga_specific_team_slug(team_name: str, liga_id: int) -> Optional[str]:
    """Gibt ligen-spezifische Team-Slugs zurück (für direkte Mappings)"""
    if liga_id == 99:  # Konferenz - verwendet Bundesliga-Mappings
        # Versuche zuerst 1. Bundesliga, dann 2. Bundesliga
        mapping = {
            # 1. Bundesliga Teams
            "FC Bayern München": "bayern",
            "Bayern München": "bayern",
            "Bayern": "bayern",
            "FC Bayern": "bayern",
            "Borussia Dortmund": "dortmund",
            "BVB": "dortmund",
            "RB Leipzig": "rbleipzig",
            "Leipzig": "rbleipzig",
            "RasenBallsport Leipzig": "rbleipzig",
            "Bayer 04 Leverkusen": "leverkusen",
            "Leverkusen": "leverkusen",
            "Bayer Leverkusen": "leverkusen",
            "VfB Stuttgart": "stuttgart",
            "Stuttgart": "stuttgart",
            "Eintracht Frankfurt": "frankfurt",
            "Frankfurt": "frankfurt",
            "Eintracht": "frankfurt",
            "SC Freiburg": "freiburg",
            "Freiburg": "freiburg",
            "TSG 1899 Hoffenheim": "hoffenheim",
            "Hoffenheim": "hoffenheim",
            "TSG Hoffenheim": "hoffenheim",
            "1899 Hoffenheim": "hoffenheim",
            "VfL Wolfsburg": "wolfsburg",
            "Wolfsburg": "wolfsburg",
            "Borussia Mönchengladbach": "mgladbach",
            "Mönchengladbach": "mgladbach",
            "Borussia M'gladbach": "mgladbach",
            "1. FSV Mainz 05": "mainz",
            "Mainz 05": "mainz",
            "Mainz": "mainz",
            "FSV Mainz": "mainz",
            "1. FC Union Berlin": "unionberlin",
            "Union Berlin": "unionberlin",
            "Union": "unionberlin",
            "FC Union Berlin": "unionberlin",
            "FC Augsburg": "augsburg",
            "Augsburg": "augsburg",
            "1. FC Heidenheim": "heidenheim",
            "Heidenheim": "heidenheim",
            "FC Heidenheim": "heidenheim",
            "1. FC Heidenheim 1846": "heidenheim",
            "1. FC Köln": "koeln",
            "FC Köln": "koeln",
            "Köln": "koeln",
            "Werder Bremen": "bremen",
            "SV Werder Bremen": "bremen",
            "Bremen": "bremen",
            "Werder": "bremen",
            "Hamburger SV": "hamburg",
            "HSV": "hamburg",
            "Hamburg": "hamburg",
            "Hamburger": "hamburg",
            "FC St. Pauli": "stpauli",
            "St. Pauli": "stpauli",
            "St Pauli": "stpauli",
            # 2. Bundesliga Teams
            "Holstein Kiel": "kiel",
            "Kiel": "kiel",
            "Holstein": "kiel",
            "VfL Bochum": "vflbochum",
            "Bochum": "vflbochum",
            "SV Elversberg": "elversberg",
            "Elversberg": "elversberg",
            "SV 07 Elversberg": "elversberg",
            "SC Paderborn 07": "paderborn",
            "Paderborn 07": "paderborn",
            "Paderborn": "paderborn",
            "SC Paderborn": "paderborn",
            "1. FC Magdeburg": "magdeburg",
            "Magdeburg": "magdeburg",
            "FC Magdeburg": "magdeburg",
            "Fortuna Düsseldorf": "duesseldorf",
            "Düsseldorf": "duesseldorf",
            "Fortuna": "duesseldorf",
            "1. FC Kaiserslautern": "klautern",
            "Kaiserslautern": "klautern",
            "FC Kaiserslautern": "klautern",
            "Karlsruher SC": "karlsruhe",
            "Karlsruhe": "karlsruhe",
            "Karlsruher": "karlsruhe",
            "KSC": "karlsruhe",
            "Hannover 96": "hannover",
            "Hannover": "hannover",
            "1. FC Nürnberg": "nuernberg",
            "Nürnberg": "nuernberg",
            "FC Nürnberg": "nuernberg",
            "Hertha BSC": "herthabsc",
            "Hertha BSC Berlin": "herthabsc",
            "Hertha": "herthabsc",
            "Hertha Berlin": "herthabsc",
            "SV Darmstadt 98": "darmstadt",
            "Darmstadt 98": "darmstadt",
            "Darmstadt": "darmstadt",
            "SV Darmstadt": "darmstadt",
            "SpVgg Greuther Fürth": "fuerth",
            "Greuther Fürth": "fuerth",
            "Fürth": "fuerth",
            "Greuther": "fuerth",
            "FC Schalke 04": "schalke",
            "Schalke 04": "schalke",
            "Schalke": "schalke",
            "FC Schalke": "schalke",
            "SC Preußen Münster": "muenster",
            "Preußen Münster": "muenster",
            "Münster": "muenster",
            "Preussen Muenser": "muenster",
            "Eintracht Braunschweig": "braunschweig",
            "Braunschweig": "braunschweig",
            "Eintracht BS": "braunschweig",
            "DSC Arminia Bielefeld": "bielefeld",
            "Arminia Bielefeld": "bielefeld",
            "Bielefeld": "bielefeld",
            "Arminia": "bielefeld",
            "Dynamo Dresden": "dresden",
            "SG Dynamo Dresden": "dresden",
        }
        return mapping.get(team_name)
    
    elif liga_id == 21:  # Frankreich (Ligue 1)
        mapping = {
            "Paris Saint-Germain": "psg",
            "Paris St. Germain": "psg",
            "PSG": "psg",
            "Paris FC": "parisfc",
            "FC Lorient": "lorient",
            "Lorient": "lorient",
            "Olympique de Marseille": "ol.marseille",
            "Olympique Marseille": "ol.marseille",
            "Marseille": "ol.marseille",
            "Olympique Lyon": "lyon",
            "Olympique de Lyon": "lyon",
            "Lyon": "lyon",
            "AS Monaco": "monaco",
            "Monaco": "monaco",
            "OGC Nizza": "nizza",
            "OGC Nice": "nizza",
            "Nizza": "nizza",
            "Nice": "nizza",
            "RC Strassburg": "strassburg",
            "RC Strasbourg": "strassburg",
            "Strassburg": "strassburg",
            "Strasbourg": "strassburg",
            "LOSC Lille": "lille",
            "Lille": "lille",
            "Stade Rennais": "rennes",
            "Stade Rennes": "rennes",
            "Rennes": "rennes",
            "FC Nantes": "nantes",
            "Nantes": "nantes",
            "Montpellier HSC": "montpellier-hsc",
            "Montpellier": "montpellier-hsc",
            "RC Lens": "lens",
            "Lens": "lens",
            "Toulouse FC": "toulouse",
            "FC Toulouse": "toulouse",
            "Toulouse": "toulouse",
            "Stade Brestois 29": "brest",
            "Stade Brestois": "brest",
            "Brest": "brest",
            "FC Metz": "fcmetz",
            "Metz": "fcmetz",
            "Fcmetz": "fcmetz",
            "Le Havre AC": "aclehavre",
            "AC Le Havre": "aclehavre",
            "Le Havre": "aclehavre",
            "Havre": "aclehavre",
            "Clermont Foot": "clermont-foot",
            "Clermont": "clermont-foot",
            "Stade de Reims": "stade-reims",
            "Stade Reims": "stade-reims",
            "Reims": "stade-reims",
            "AC Troyes": "troyes-ac",
            "Troyes AC": "troyes-ac",
            "Troyes": "troyes-ac",
            "AJ Auxerre": "auxerre",
            "Auxerre": "auxerre",
        }
        return mapping.get(team_name)
    
    elif liga_id == 41:  # Spanien (La Liga)
        mapping = {
            "Deportivo Alavés SAD": "alaves",
            "Deportivo Alavés": "alaves",
            "Alavés": "alaves",
            "Alaves": "alaves",
            "RCD Espanyol": "espanyol",
            "Espanyol Barcelona": "espanyol",
            "Espanyol": "espanyol",
            "Real Betis": "realbetis",
            "Real Betis Balompié": "realbetis",
            "Real Betis Sevilla": "realbetis",
            "Betis": "realbetis",
            "RCD Mallorca": "mallorca",
            "Mallorca": "mallorca",
            "Real Oviedo": "oviedo",
            "Oviedo": "oviedo",
            "Club Atlético Osasuna": "osasuna",
            "CA Osasuna": "osasuna",
            "Osasuna": "osasuna",
            "FC Barcelona": "fcbarcelona",
            "Barcelona": "fcbarcelona",
            "Real Madrid": "realmadrid",
            "Real Madrid CF": "realmadrid",
            "Atlético Madrid": "atlmadrid",
            "Atletico Madrid": "atlmadrid",
            "Atletico": "atlmadrid",
            "Valencia CF": "valencia",
            "Valencia": "valencia",
            "Sevilla FC": "sevilla",
            "Sevilla": "sevilla",
            "Athletic Bilbao": "athbilbao",
            "Athletic Club Bilbao": "athbilbao",
            "Villarreal CF": "villarreal",
            "Villarreal": "villarreal",
            "Real Sociedad": "realsociedad",
            "Sociedad": "realsociedad",
            "Getafe CF": "getafe",
            "Getafe": "getafe",
            "Cádiz CF": "cadiz",
            "Cadiz CF": "cadiz",
            "Cádiz": "cadiz",
            "Cadiz": "cadiz",
            "RC Celta Vigo": "celtavigo",
            "Celta de Vigo": "celtavigo",
            "Celta Vigo": "celtavigo",
            "Celta": "celtavigo",
            "Rayo Vallecano": "vallecano",
            "Vallecano": "vallecano",
            "Granada CF": "granada-cf",
            "Granada": "granada-cf",
            "UD Las Palmas": "ud-las-palmas",
            "Las Palmas": "ud-las-palmas",
            "UD Almería": "almeria",
            "UD Almeria": "almeria",
            "Almería": "almeria",
            "Almeria": "almeria",
            "Levante UD": "levante",
            "Levante": "levante",
            "Real Valladolid CF": "valladolid",
            "Real Valladolid": "valladolid",
            "Valladolid": "valladolid",
            "Elche CF": "elche",
            "Elche": "elche",
            "SD Huesca": "huesca",
            "Huesca": "huesca",
            "SD Eibar": "eibar",
            "Eibar": "eibar",
        }
        return mapping.get(team_name)
    
    elif liga_id == 51:  # England (Premier League)
        mapping = {
            "Crystal Palace FC": "crystalpalace",
            "Crystal Palace": "crystalpalace",
            "Brentford FC": "brentford",
            "Brentford": "brentford",
            "Manchester City FC": "mancity",
            "Manchester City": "mancity",
            "Man City": "mancity",
            "Liverpool FC": "liverpool",
            "Liverpool": "liverpool",
            "Chelsea": "chelsea",
            "Chelsea FC": "chelsea",
            "Arsenal FC": "arsenal",
            "Arsenal": "arsenal",
            "Tottenham Hotspur": "tottenham",
            "Tottenham": "tottenham",
            "Tottenham Hotspur FC": "tottenham",
            "Manchester United FC": "man.united",
            "Manchester United": "man.united",
            "Newcastle United FC": "newcastle",
            "Newcastle United": "newcastle",
            "Newcastle": "newcastle",
            "Leicester City FC": "leicester",
            "Leicester City": "leicester",
            "West Ham United FC": "westham",
            "West Ham United": "westham",
            "West Ham": "westham",
            "Brighton & Hove Albion FC": "brighton",
            "Brighton & Hove Albion": "brighton",
            "Brighton": "brighton",
            "Wolverhampton Wanderers FC": "wolverhampton",
            "Wolverhampton Wanderers": "wolverhampton",
            "Wolves": "wolverhampton",
            "Wolverhampton": "wolverhampton",
            "Leeds United FC": "leedsunited",
            "Leeds United": "leedsunited",
            "Leeds": "leedsunited",
            "Aston Villa FC": "astonvilla",
            "Aston Villa": "astonvilla",
            "Everton FC": "everton",
            "Everton": "everton",
            "Nottingham Forest FC": "nottingham",
            "Nottingham Forest": "nottingham",
            "Luton Town FC": "lutontown",
            "Luton Town": "lutontown",
            "Burnley FC": "burnley",
            "Burnley": "burnley",
            "Sheffield United FC": "sheffieldunited",
            "Sheffield United": "sheffieldunited",
            "Ipswich Town FC": "ipswichtown",
            "Ipswich Town": "ipswichtown",
            "Southampton FC": "southampton",
            "Southampton": "southampton",
            "Norwich City FC": "norwichcity",
            "Norwich City": "norwichcity",
            "Watford FC": "watford",
            "Watford": "watford",
            "Fulham FC": "fulham",
            "Fulham": "fulham",
            "AFC Bournemouth": "bournemouth",
            "Bournemouth": "bournemouth",
        }
        return mapping.get(team_name)
    
    elif liga_id == 2:  # 2. Bundesliga
        mapping = {
            "Holstein Kiel": "holsteinkiel",
            "Kiel": "holsteinkiel",
            "Holstein": "holsteinkiel",
            "VfL Bochum": "vflbochum",
            "Bochum": "vflbochum",
            "SV Elversberg": "elversberg",
            "Elversberg": "elversberg",
            "SV 07 Elversberg": "elversberg",
            "SC Paderborn 07": "paderborn",
            "Paderborn 07": "paderborn",
            "Paderborn": "paderborn",
            "SC Paderborn": "paderborn",
            "1. FC Magdeburg": "magdeburg",
            "Magdeburg": "magdeburg",
            "FC Magdeburg": "magdeburg",
            "Fortuna Düsseldorf": "duesseldorf",
            "Düsseldorf": "duesseldorf",
            "Fortuna": "duesseldorf",
            "1. FC Kaiserslautern": "klautern",
            "Kaiserslautern": "klautern",
            "FC Kaiserslautern": "klautern",
            "Karlsruher SC": "karlsruhe",
            "Karlsruhe": "karlsruhe",
            "Karlsruher": "karlsruhe",
            "KSC": "karlsruhe",
            "Hannover 96": "hannover",
            "Hannover": "hannover",
            "1. FC Nürnberg": "nuernberg",
            "Nürnberg": "nuernberg",
            "FC Nürnberg": "nuernberg",
            "Hertha BSC": "herthabsc",
            "Hertha BSC Berlin": "herthabsc",
            "Hertha": "herthabsc",
            "Hertha Berlin": "herthabsc",
            "SV Darmstadt 98": "darmstadt",
            "Darmstadt 98": "darmstadt",
            "Darmstadt": "darmstadt",
            "SV Darmstadt": "darmstadt",
            "SpVgg Greuther Fürth": "fuerth",
            "Greuther Fürth": "fuerth",
            "Fürth": "fuerth",
            "Greuther": "fuerth",
            "FC Schalke 04": "schalke",
            "Schalke 04": "schalke",
            "Schalke": "schalke",
            "FC Schalke": "schalke",
            "SC Preußen Münster": "muenster",
            "Preußen Münster": "muenster",
            "Münster": "muenster",
            "Preussen Muenser": "muenster",
            "Eintracht Braunschweig": "braunschweig",
            "Braunschweig": "braunschweig",
            "Eintracht BS": "braunschweig",
            "DSC Arminia Bielefeld": "bielefeld",
            "Arminia Bielefeld": "bielefeld",
            "Bielefeld": "bielefeld",
            "Arminia": "bielefeld",
            "Dynamo Dresden": "dresden",
            "SG Dynamo Dresden": "dresden",
        }
        return mapping.get(team_name)
    
    elif liga_id == 3:  # DFB-Pokal
        mapping = {
            # 1. Bundesliga Teams
            "FC Bayern München": "bayern",
            "Bayern München": "bayern",
            "Bayern": "bayern",
            "FC Bayern": "bayern",
            "Borussia Dortmund": "dortmund",
            "BVB": "dortmund",
            "RB Leipzig": "rbleipzig",
            "Leipzig": "rbleipzig",
            "RasenBallsport Leipzig": "rbleipzig",
            "Bayer 04 Leverkusen": "leverkusen",
            "Leverkusen": "leverkusen",
            "Bayer Leverkusen": "leverkusen",
            "VfB Stuttgart": "stuttgart",
            "Stuttgart": "stuttgart",
            "Eintracht Frankfurt": "frankfurt",
            "Frankfurt": "frankfurt",
            "Eintracht": "frankfurt",
            "SC Freiburg": "freiburg",
            "Freiburg": "freiburg",
            "TSG 1899 Hoffenheim": "hoffenheim",
            "Hoffenheim": "hoffenheim",
            "TSG Hoffenheim": "hoffenheim",
            "1899 Hoffenheim": "hoffenheim",
            "VfL Wolfsburg": "wolfsburg",
            "Wolfsburg": "wolfsburg",
            "Borussia Mönchengladbach": "mgladbach",
            "Mönchengladbach": "mgladbach",
            "Borussia M'gladbach": "mgladbach",
            "1. FSV Mainz 05": "mainz",
            "Mainz 05": "mainz",
            "Mainz": "mainz",
            "FSV Mainz": "mainz",
            "1. FC Union Berlin": "unionberlin",
            "Union Berlin": "unionberlin",
            "Union": "unionberlin",
            "FC Union Berlin": "unionberlin",
            "FC Augsburg": "augsburg",
            "Augsburg": "augsburg",
            "1. FC Heidenheim": "heidenheim",
            "Heidenheim": "heidenheim",
            "FC Heidenheim": "heidenheim",
            "1. FC Köln": "koeln",
            "FC Köln": "koeln",
            "Köln": "koeln",
            "Werder Bremen": "bremen",
            "SV Werder Bremen": "bremen",
            "Bremen": "bremen",
            "Werder": "bremen",
            "Hamburger SV": "hamburg",
            "HSV": "hamburg",
            "Hamburg": "hamburg",
            "Hamburger": "hamburg",
            "FC St. Pauli": "stpauli",
            "St. Pauli": "stpauli",
            "St Pauli": "stpauli",
            # 2. Bundesliga Teams
            "Holstein Kiel": "kiel",
            "Kiel": "kiel",
            "Holstein": "kiel",
            "VfL Bochum": "vflbochum",
            "Bochum": "vflbochum",
            "SV Elversberg": "elversberg",
            "Elversberg": "elversberg",
            "SV 07 Elversberg": "elversberg",
            "SC Paderborn 07": "paderborn",
            "Paderborn 07": "paderborn",
            "Paderborn": "paderborn",
            "SC Paderborn": "paderborn",
            "1. FC Magdeburg": "magdeburg",
            "Magdeburg": "magdeburg",
            "FC Magdeburg": "magdeburg",
            "Fortuna Düsseldorf": "duesseldorf",
            "Düsseldorf": "duesseldorf",
            "Fortuna": "duesseldorf",
            "1. FC Kaiserslautern": "klautern",
            "Kaiserslautern": "klautern",
            "FC Kaiserslautern": "klautern",
            "Karlsruher SC": "karlsruhe",
            "Karlsruhe": "karlsruhe",
            "Karlsruher": "karlsruhe",
            "KSC": "karlsruhe",
            "Hannover 96": "hannover",
            "Hannover": "hannover",
            "1. FC Nürnberg": "nuernberg",
            "Nürnberg": "nuernberg",
            "FC Nürnberg": "nuernberg",
            "Hertha BSC": "herthabsc",
            "Hertha BSC Berlin": "herthabsc",
            "Hertha": "herthabsc",
            "Hertha Berlin": "herthabsc",
            "SV Darmstadt 98": "darmstadt",
            "Darmstadt 98": "darmstadt",
            "Darmstadt": "darmstadt",
            "SV Darmstadt": "darmstadt",
            "SpVgg Greuther Fürth": "fuerth",
            "Greuther Fürth": "fuerth",
            "Fürth": "fuerth",
            "Greuther": "fuerth",
            "FC Schalke 04": "schalke",
            "Schalke 04": "schalke",
            "Schalke": "schalke",
            "FC Schalke": "schalke",
            "SC Preußen Münster": "muenster",
            "Preußen Münster": "muenster",
            "Münster": "muenster",
            "Preussen Muenser": "muenster",
            "Eintracht Braunschweig": "braunschweig",
            "Braunschweig": "braunschweig",
            "Eintracht BS": "braunschweig",
            "DSC Arminia Bielefeld": "bielefeld",
            "Arminia Bielefeld": "bielefeld",
            "Bielefeld": "bielefeld",
            "Arminia": "bielefeld",
            "Dynamo Dresden": "dresden",
            "SG Dynamo Dresden": "dresden",
            "Hansa Rostock": "hansarostock",
            "FC Hansa Rostock": "hansarostock",
            "Rostock": "hansarostock",
            "Hansa": "hansarostock",
            "SSV Jahn Regensburg": "regensburg",
            "Jahn Regensburg": "regensburg",
            "Regensburg": "regensburg",
            "Jahn": "regensburg",
            "FC Erzgebirge Aue": "aue",
            "Erzgebirge Aue": "aue",
            "Aue": "aue",
            "Erzgebirge": "aue",
            "VfL Osnabrück": "osnabrueck",
            "Osnabrück": "osnabrueck",
            "Osnabrueck": "osnabrueck",
        }
        return mapping.get(team_name)
    
    elif liga_id == 31:  # Italien (Serie A)
        mapping = {
            "Juventus Turin": "juventusturin",
            "Juventus": "juventusturin",
            "Inter Mailand": "intermailand",
            "Inter": "intermailand",
            "AC Mailand": "acmailand",
            "AC Milan": "acmailand",
            "Mailand": "acmailand",
            "AS Rom": "asrom",
            "AS Roma": "asrom",
            "Rom": "asrom",
            "Roma": "asrom",
            "SSC Napoli": "napoli",
            "Napoli": "napoli",
            "Atalanta Bergamo": "bergamo",
            "Atalanta": "bergamo",
            "Bergamo": "bergamo",
            "AC Florenz": "acflorenz",
            "AC Fiorentina": "acflorenz",
            "Florenz": "acflorenz",
            "Fiorentina": "acflorenz",
            "Lazio Rom": "laziorom",
            "Lazio": "laziorom",
            "Lazio Roma": "laziorom",
            "Bologna FC 1909": "bologna",
            "FC Bologna": "bologna",
            "Bologna": "bologna",
            "Torino FC": "torino",
            "Torino": "torino",
            "Udinese Calcio": "udinese",
            "Udinese": "udinese",
            "US Sassuolo Calcio": "sassuolo",
            "US Sassuolo": "sassuolo",
            "Sassuolo": "sassuolo",
            "Genoa CFC": "cfcgenua",
            "Genoa": "cfcgenua",
            "CFC Genua": "cfcgenua",
            "Genua": "cfcgenua",
            "Cagliari Calcio": "cagliari",
            "Cagliari": "cagliari",
            "Frosinone Calcio": "frosinone",
            "Frosinone": "frosinone",
            "US Lecce": "lecce",
            "Lecce": "lecce",
            "Hellas Verona FC": "hverona",
            "Hellas Verona": "hverona",
            "Verona": "hverona",
            "H. Verona": "hverona",
            "Empoli FC": "empoli",
            "Empoli": "empoli",
            "AC Monza": "monza",
            "Monza": "monza",
            "US Salernitana 1919": "salernitana",
            "US Salernitana": "salernitana",
            "Salernitana": "salernitana",
            "Como Calcio": "como",
            "Como": "como",
            "US Cremonese": "cremonese",
            "Cremonese": "cremonese",
            "FC Turin": "turin",
            "Turin": "turin",
            "Pisa Calcio": "pisa",
            "Pisa": "pisa",
            "Parma Calcio": "parma",
            "Parma": "parma",
        }
        return mapping.get(team_name)
    
    return None

def vereinfache_team_name_fuer_vergleich(team_name: str, liga_id: int = 1) -> str:
    """Vereinfacht Team-Namen für fussballdaten.de URLs - Portierung der App-Logik"""
    if not team_name:
        return ""
    
    # Spezifische Mappings basierend auf Liga
    liga_specific_slug = get_liga_specific_team_slug(team_name, liga_id)
    if liga_specific_slug:
        return liga_specific_slug
    
    # Unicode-Normalisierung (wie Normalizer.normalize in Kotlin)
    slug = unicodedata.normalize('NFD', team_name)
    # Entferne diakritische Zeichen (wie .replace(Regex("\\p{M}+"), ""))
    slug = ''.join(c for c in slug if unicodedata.category(c) != 'Mn')
    slug = slug.lower()
    slug = slug.replace("ß", "ss")
    
    # Entferne Präfixe und Vereinsbegriffe (für deutsche Ligen + Konferenz)
    if liga_id in [1, 2, 3, 99]:
        # Entferne "1.", "2.", "3."
        slug = re.sub(r'\b(1\.|2\.|3\.)\s*', '', slug)
        # Entferne Vereinsbegriffe am Anfang
        slug = re.sub(r'\b(fc|sv|fsv|vfl|vfb|tsg|sc|spvgg|eintracht|fortuna|arminia|preußen|preussen)\s+', '', slug)
        # Entferne Vereinsbegriffe am Ende
        slug = re.sub(r'\s+(fc|sv|fsv|vfl|vfb|tsg|sc|spvgg|eintracht|fortuna|arminia|preußen|preussen)\b', '', slug)
    
    # Für andere Ligen: Entferne Standard-Präfixe
    if liga_id not in [1, 2, 3, 99]:
        slug = re.sub(r'\b(fc|as|rc|osc|ogc|stade|olympique|le)\s+', '', slug)
        slug = re.sub(r'\s+(fc|ac|hsc|cv)\b', '', slug)
    
    # Leerzeichen und Sonderzeichen entfernen
    slug = re.sub(r'[^a-z0-9]', '', slug)
    
    # Spezielle Mappings für bekannte Unterschiede (deutsche Ligen + Konferenz)
    if liga_id in [1, 2, 3, 99]:
        slug_mappings = {
            "bayernmunchen": "bayern",
            "fcbayernmunchen": "bayern",
            "fcbayern": "bayern",
            "borussiadortmund": "dortmund",
            "bvb": "dortmund",
            "borussiamonchengladbach": "mgladbach",
            "monchengladbach": "mgladbach",
            "werderbremen": "bremen",
            "svwerderbremen": "bremen",
            "svwerder": "bremen",
            "heidenheim1846": "heidenheim",
            "fcheidenheim1846": "heidenheim",
            "fcheidenheim": "heidenheim",
            "1heidenheim1846": "heidenheim",
            "1fcheidenheim1846": "heidenheim",
            "koln": "koeln",
            "fckoln": "koeln",
            "fckoeln": "koeln",
            "1fckoln": "koeln",
            "1fckoeln": "koeln",
            "koeln": "koeln",
            "dusseldorf": "duesseldorf",
            "fortunadusseldorf": "duesseldorf",
            "fortunaduesseldorf": "duesseldorf",
            "herthabsc": "herthabsc",
            "herthabscc": "herthabsc",
            "hoffenheim": "hoffenheim",
            "1899hoffenheim": "hoffenheim",
            "tsghoffenheim": "hoffenheim",
            "rbleipzig": "rbleipzig",
            "leipzigrb": "rbleipzig",
            "unionberlin": "unionberlin",
            "fcunionberlin": "unionberlin",
            "1unionberlin": "unionberlin",
            "1fcunionberlin": "unionberlin",
            "stpauli": "stpauli",
            "fcstpauli": "stpauli",
            "mainz05": "mainz",
            "fsvmainz05": "mainz",
            "mainz": "mainz",
            "1fsvmainz05": "mainz",
            "hamburger": "hamburg",
            "hamburgersv": "hamburg",
            "hsv": "hamburg",
            "stuttgart": "stuttgart",
            "vfbstuttgart": "stuttgart",
            "freiburg": "freiburg",
            "scfreiburg": "freiburg",
            "frankfurt": "frankfurt",
            "eintrachtfrankfurt": "frankfurt",
            "eintracht": "frankfurt",
            "bayer04leverkusen": "leverkusen",
            "bayerleverkusen": "leverkusen",
            "bayer04": "leverkusen",
            "leverkusen04": "leverkusen",
            "hannover96": "hannover",
            "schalke04": "schalke",
            "paderborn07": "paderborn",
            "kaiserslautern": "klautern",
            "1fckaiserslautern": "klautern",
            "karlsruher": "karlsruhe",
            "darmstadt98": "darmstadt",
            "07elversberg": "elversberg",
            "elversberg07": "elversberg",
            "greutherfurth": "fuerth",
            "greuterfurth": "fuerth",
            "bochum": "vflbochum",
            "dynamodresden": "dresden",
            "preussenmuenster": "muenster",
            "arminiabielefeld": "bielefeld",
        }
        slug = slug_mappings.get(slug, slug)
    
    return slug

def convert_international_team_to_slug(team_name: str) -> str:
    """Konvertiert internationale Team-Namen zu Slugs - Portierung der App-Logik"""
    # Spezial-Mapping für Aufstellungs-URLs - EXAKTE Schreibweise von fussballdaten.de!
    aufstellung_mapping = {
        # Champions League
        "Slavia Prag": "slaviaprag",
        "Arsenal FC": "arsenal",
        "SSC Napoli": "sscneapel",
        "Eintracht Frankfurt": "frankfurt",
        "Olympiakos Piräus": "olympiakos",
        "PSV Eindhoven": "eindhoven",
        "Atlético Madrid": "atlmadrid",
        "Royale Union Saint-Gilloise": "stgilloise",
        "FK Bodø/Glimt": "bodo/glimt",
        "AS Monaco": "monaco",
        "Juventus Turin": "juventusturin",
        "Sporting Lissabon": "sporting",
        "Liverpool FC": "liverpool",
        "Real Madrid CF": "realmadrid",
        "Tottenham Hotspur FC": "tottenham",
        "FC Kopenhagen": "kopenhagen",
        "Paris Saint-Germain": "psg",
        "FC Bayern München": "bayern",
        "AEP Paphos FC": "aeppaphosfc",
        "Villarreal CF": "villarreal",
        "FK Qarabağ Ağdam": "karabakh",
        "Chelsea FC": "chelsea",
        "Olympique de Marseille": "olmarseille",
        "Atalanta Bergamo": "bergamo",
        "Newcastle United FC": "newcastle",
        "Athletic Club Bilbao": "athbilbao",
        "Manchester City FC": "mancity",
        "Borussia Dortmund": "dortmund",
        "Club Brugge KV": "clubbrugge",
        "FC Barcelona": "fcbarcelona",
        "Inter Mailand": "intermailand",
        "FC Kairat Almaty": "kairat",
        "Ajax Amsterdam": "ajaxamsterdam",
        "Galatasaray Istanbul": "galatasaray",
        "Benfica Lissabon": "benfica",
        "Bayer 04 Leverkusen": "leverkusen",
        # Europa League
        "FC Basel 1893": "fcbasel",
        "Steaua Bukarest": "steaua",
        "Malmö FF": "malmoeff",
        "Panathinaikos Athen": "panathinaikos",
        "SK Sturm Graz": "sturmgraz",
        "Nottingham Forest FC": "nottingham",
        "Roter Stern Belgrad": "rsbelgrad",
        "LOSC Lille": "lille",
        "FC Utrecht": "utrecht",
        "FC Porto": "porto",
        "GNK Dinamo Zagreb": "dzagreb",
        "RC Celta de Vigo": "celtavigo",
        "OGC Nizza": "nizza",
        "SC Freiburg": "freiburg",
        "FC Red Bull Salzburg": "salzburg",
        "Go Ahead Eagles": "deventer",
        "FC Midtjylland": "midtjylland",
        "Celtic Glasgow": "cglasgow",
        "FC Viktoria Pilsen": "pilsen",
        "Fenerbahçe Istanbul": "fenerbahce",
        "Real Betis": "realbetis",
        "Olympique Lyon": "lyon",
        "VfB Stuttgart": "stuttgart",
        "Feyenoord Rotterdam": "feyenoord",
        "PAOK Thessaloniki FC": "paoksaloniki",
        "Young Boys Bern": "ybbern",
        "Bologna FC 1909": "bologna",
        "SK Brann": "bergen",
        "Aston Villa FC": "astonvilla",
        "Maccabi Tel Aviv FC": "mtelaviv",
        "Glasgow Rangers": "glrangers",
        "AS Rom": "asrom",
        "Ferencvárosi Torna Club": "ferencvarosi",
        "PFC Ludogorets Razgrad": "ludogorets",
        "Sporting Braga": "braga",
        "KRC Genk": "genk",
        # Conference League
        "FSV Mainz 05": "mainz",
        "AC Florenz": "acflorenz",
        "NK Celje": "celje",
        "Legia Warschau": "lwarschau",
        "Kuopion Palloseura": "kuopiops",
        "ŠK Slovan Bratislava": "skslovan",
        "Samsunspor": "samsunspor",
        "Ħamrun Spartans FC": "hamrunspart",
        "FC Noah": "fcnoah",
        "SK Sigma Olomouc": "olomouc",
        "FC Shakhtar Donetsk": "shakhtar",
        "Breiðablik Kópavogur": "kopavogur",
        "AC Sparta Prag": "spartaprag",
        "KS Raków Częstochowa": "ksrakowczest",
        "AEK Athen": "aekathen",
        "Shamrock Rovers FC": "shamrock",
        "AEK Larnaca FC": "larnaka",
        "Aberdeen FC": "aberdeen",
        "BK Häcken": "bkhaecken",
        "RC Strassburg": "strassburg",
        "SK Rapid Wien": "rapidwien",
        "CS Universitatea Craiova": "craiova",
        "Shelbourne FC": "shelbourne",
        "KF Drita": "kfdrita",
        "FC Dynamo Kiev": "dynamokiev",
        "HŠK Zrinjski Mostar": "mostar",
        "FK Shkëndija Tetovo": "tetovo",
        "Jagiellonia Białystok": "jagiellonia",
        "Lincoln Red Imps FC": "lincolnfc",
        "HNK Rijeka": "rijeka",
        "Rayo Vallecano": "vallecano",
        "KKS Lech Poznań": "poznan",
        "Crystal Palace FC": "crystalpalace",
        "AZ Alkmaar": "alkmaar",
        "FC Lausanne-Sport": "lausanne",
        "AC Omonia": "omnikosia",
    }
    
    if team_name in aufstellung_mapping:
        return aufstellung_mapping[team_name]
    
    # Fallback: Vereinfachte Konvertierung
    slug = team_name.lower().replace(" ", "").replace("-", "")
    return slug

def convert_team_to_slug(team_name: str, liga_id: int = 1, is_international: bool = False) -> str:
    """Hauptfunktion: Konvertiert Team-Namen zu URL-Slugs"""
    if is_international:
        return convert_international_team_to_slug(team_name)
    else:
        return vereinfache_team_name_fuer_vergleich(team_name, liga_id)

